services:
  arbre-aux-wc:
    image: ghcr.io/bachrc/de-l-arbre-aux-wc:latest
    container_name: arbre-aux-wc
    ports:
      - 8080:8080
    environment:
      UID: '1000'
      GID: '1000'
    volumes:
      - '/pb/pb_data'
